### ISSUE TITLE
League Leaders

### ISSUE THREAD

**Issue by jbowdle** [blackshane/super-team-project#4]
# League Leaders 

## User Story
As a football fan
I would like to see stats for the teams I search for
So that I can know more about that team

## Acceptance Criteria
GIVEN that I am on the stats page
WHEN I open the page
THEN there will be an option to search for teams
WHEN I click on a team
THEN it will display various stats for the team

GIVEN that I am on the stats page and I have favorited a team
WHEN I open the page
THEN my favorited team will already have its stats displayed

**Comment by Gr1ssom** [comment]
finished, needs CSS as of 5:40pm 3/26/23
