### ISSUE TITLE
Standings

### ISSUE THREAD

**Issue by jbowdle** [blackshane/super-team-project#7]
# Standings

## User Story
As a football fan
I want to see the standings of various leagues
So I can see how my favorite team in that league is performing

## Acceptance Criteria
WHEN I open the standings page
THEN I can see the standings for MLS (Major League Soccer)
WHEN I click on a team name
THEN I am taken to their team page

**Comment by Gr1ssom** [comment]
![STANDINGS copy](https://user-images.githubusercontent.com/123666763/225784698-ba9ef38b-ebfd-4e7c-b330-0384977052de.jpg)

**Comment by Gr1ssom** [comment]
colors are b&w just to get a framework built, not styling

**Comment by Gr1ssom** [comment]
submitted pull request; basic html JS and CSS done. needs further styling

**Comment by jbowdle** [comment]
All acceptance criteria met
